name: test

on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DENO_DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      ENTRYPOINT: main.ts
      GH_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
      GH_REF: ${{ github.event.ref }}
      PROD_PROJECT: ${{ secrets.PROD_PROJECT }}
      PROD_PUBLIC_KEY: ${{ secrets.PROD_PUBLIC_KEY }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: vx.x.x

      - name: Cache deps
        run: |
          deno cache $ENTRYPOINT
          deno cache build.ts

      - name: Run build
        run: |
          deno run --allow-env --check build.ts

      - name: Deploy to Deno Deploy
        run: |
          deno install --allow-net --allow-env --allow-read https://deno.land/x/deploy/deployctl.ts
          deployctl deploy -p=$PROJECT $ENTRYPOINT
